
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 75757755
      MYSQL_DATABASE: fsd
      MYSQL_USER: root
      MYSQL_PASSWORD: 75757755
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend-service
    working_dir: /src/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: 75757755
      DB_DATABASE: fsd
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql-data:


